version: "3.9"

services:
  pgdatabase:
    container_name: pgdatabase
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgresdb
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword1_
    networks:
      - web-app-network

  backend:
    build: ./WebBackend
    restart: unless-stopped
    depends_on:
      - pgdatabase
    ports:
      - "9000:80"
    networks:
      - web-app-network

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx:/etc/nginx/conf.d
    networks:
      - web-app-network

volumes:
  pg-data:
    driver: local

networks:
  web-app-network:
    driver: bridge